### ISSUE TITLE
E_FONT_TXT5 not declared for code generated for number input

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#49] opened 2019-12-31 12:22 UTC
I found the bug for builder 0.13.0.3 but not sure if it got fixed after the version (cuz I couldn't generate code for numer input after updated). It's probably related to issue #48 I just reported. The generated code gives compilation error when the font of a number input is not E_FONT_TXT5. I think the builder just forget to generate an enum element E_FONT_TXT5 for XKeyPad which is required by a number input. 

Here is a project with generated .ino code that demonstrates the bug. 
[gui2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4012646/gui2.zip)

Paul, thank for your fast response!

**Comment by Pconti31** [comment] 2019-12-31 14:14
really a duplicate of issue 48 so I'm closing it.
assigned bug 125.

**Comment by Pconti31** [comment] 2019-12-31 14:57
Turns out not to be a dup of #48 so I have reopened and assigned bug 126.
Paul--

**Comment by Pconti31** [comment] 2019-12-31 15:42
bug is fixed in 0.13.b010 and as you pointed out only needed to add keyboard font even when its not used elsewhere.
Paul--

**Closed** 2019-12-31 16:27 UTC
