### ISSUE TITLE
Fatal Error Crash on "Generate Code"

### ISSUE THREAD

**Issue by manoharnayak** [ImpulseAdventure/GUIslice-Builder#203] opened 2022-05-03 18:42 UTC
**Describe the bug**
Just crashes when I try and Generate Code.

**To Reproduce**
1. Open Project File
2. Click "Generate Code"

**Expected behavior**
That it would generate my arduino code and not crash

**Crash log / Project files**

[report.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/8612858/report.zip)

**Version**
- Builder version: 0.17.b11
- OS: Ubuntu 20.04.04 LTS

**Additional context**

**Comment by Pconti31** [comment] 2022-05-03 20:54
Sorry about that. Seems the problem is with generating flash api for the toggle buttons.  I'll fix in the next release (still a few weeks away) In the meantime a quick work-around is to set Use Flash API?=false for your two toggle button.  The code generation work fine for me after that.  attached is a zip file with your project repaired.

[Hotpress.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/8614231/Hotpress.zip)

WARNING!  You are using the XSpinner class and I just fixed a major bug where the API crashes when you use this control.  Download the latest GUIslice API to fix this issue GUIslice_version.h #define GUISLICE_VER "0.17.1.3"

Paul--

**Comment by manoharnayak** [comment] 2022-05-03 21:39
thanks for the quick reply, solved my problem!

**Comment by Pconti31** [comment] 2022-09-01 19:27
fixed in release 17.b12

**Closed by Pconti31** 2022-09-01 19:27 UTC
Labels: bug
