### ISSUE TITLE
ver 0.16  crash when loading 0.15.005 project

### ISSUE THREAD

**Issue by GeorgeBoudreau** [ImpulseAdventure/GUIslice-Builder#131] opened 2020-11-13 14:10 UTC
I have a large GUIslice/GUIbuilder project consisting of 13 pages with untold elements and using the alpha and number pads.  the project builds when I use version 15.005 of the builder and library. When I update to version 16  of the library and builder the builder crashes when I open the project file.  I tried to use the new GUIslice library with my code but it will not compile due to integration of the new keyboard code.  

Not criticial but..I also noticed you cannot run builder against the guislice build examples.

[20201113_083118.txt](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5537232/20201113_083118.txt)

**Comment by Pconti31** [comment] 2020-11-13 15:08
@GeorgeBoudreau Sorry but the examples open fine.  The crash is having a problem with fonts.  What is your target platform?
What op system are you using for the Builder?
Paul--

**Comment by Pconti31** [comment] 2020-11-13 15:13
@GeorgeBoudreau Also, what size TFT screen is your target?

**Comment by GeorgeBoudreau** [comment] 2020-11-13 16:10
I am using Ubuntu 18.xx , the project runs on an ESP32-devkit-C. The screen driver is TFT-eSPI ST7796 with xpt2046 touch driver. I ran builder against the ex02_bld_btn example and there were no errors with builder or arduino and it ran as expected on the ESP32. I ran builder against ex27_bld_apha and it failed the Arduino compile.  I have attached builder and Arduino logs for ex27_bld_alpha as well as my project
[builder_logs.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5538008/builder_logs.zip)

**Comment by Pconti31** [comment] 2020-11-13 16:54
@GeorgeBoudreau Turns out the problem with this example is with Calvin's GUIslice APIlibrary.  He didn't update the examples to 0.16.  Most likely a problem with ex26_bld_calc also.  I deleted lines 139 to 172 in ex27_bld_alpha.ino and added at line 139
```
//<Keypad Callback !Start!>
//<Keypad Callback !End!>
```
Reopened the ex27_bld_alpha.prj , did a new code gen and it compiled and ran fine.
Now back to your crash I noticed you are running java 11 which is not supported.  The Builder is created with java 1.8 same as Arduino IDE.   Not sure if that caused your crash or not.  
If you zip your crashing *.prj file (I don't need your ino or header files), I will try and open it to see if I recreate your crash.

**Comment by GeorgeBoudreau** [comment] 2020-11-13 17:13
I also included the GUIslice.sh file.  I point to the java directory inside the Arduino 1.8.13 directory.
[myPRJ.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5538296/myPRJ.zip)

**Comment by Pconti31** [comment] 2020-11-13 17:47
@GeorgeBoudreau Some good news.  I can reproduce the crash.  I'll investigate and find the problem.

**Comment by GeorgeBoudreau** [comment] 2020-11-13 17:49
I did notice the fonts directories were different between 15.005 and 16.0.  Are paths hardwired?

**Comment by Pconti31** [comment] 2020-11-13 18:50
Yes.   Builder assumes working directory is GUIsliceBuilder and fonts inside there.

**Comment by Pconti31** [comment] 2020-11-13 19:22
@GeorgeBoudreau I fixed the problem.  Turned out that opening a saved project with a screen size larger than 320x240 wasn't resetting the screen dimensions so we crashed.  I fixed this and now also trap the exception. I'll post 0.16.b001 hot fix soon.
Paul--

**Comment by GeorgeBoudreau** [comment] 2020-11-13 19:25
I am using a 480x320  4" TFT display which is not that common.. a corner case.   Good catch..

**Comment by Pconti31** [comment] 2020-11-13 20:01
Fixed in Hot Fix 0.16.b001

**Closed by Pconti31** 2020-11-13 20:01 UTC

**Comment by GeorgeBoudreau** [comment] 2020-11-13 20:43
Project compiles and runs ( so far ) .  Fiddled with keypad size to fit my poor eyesight and all is well.  Thanks.

**Comment by ImpulseAdventure** [comment] 2020-11-14 07:39
As Paul mentioned, I had inadvertently overlooked updating the Builder examples for v0.16.
These have now been updated in the core GUIslice library (v0.16.0.4).

thx
