### ISSUE TITLE
Fatal error when copy-paste element selected in treeview

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#52] opened 2020-01-01 07:13 UTC
To reproduce the bug, new a project, add three texts. Select any of them **on tree view** and press Ctrl+C. Click on the simulated TFT panel and press Ctrl + V. And then the program crashed with fatal error. Or look at the following sample project if don't wanna create one. 

[gui2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4013850/gui2.zip)

Version: 0.13.0b10 on Windows.

**Comment by Pconti31** [comment] 2020-01-01 14:58
assigned bug 128.  
Paul--

**Comment by Pconti31** [comment] 2020-01-01 16:25
Investigation shows the problem is that ^c isn't being captured by the treeview so the copy command is empty.   The crash occurs because paste command wasn't checking clipboardContent for a null value.
A work-around is to use the page tab and the copy and paste buttons.  The ^v for paste will also work in this case.   Mean while I'll see why I can't get the ^c to trap.
Paul--

**Comment by Pconti31** [comment] 2020-01-01 19:21
I suspect that JTextfields inside the JTree are using a keybinding to trap the ^c so I just added 
a KeyListener to the JTree and trap the ^c, then pass along to the Controller.copyWidget() function.  That seems to be working fine so this bug will be fixed in 0.13.b011.

**Comment by Pconti31** [comment] 2020-01-03 19:24
fixed in release 0.13.b011

**Closed by Pconti31** 2020-01-03 19:25 UTC
