### ISSUE TITLE
Add fonts

### ISSUE THREAD

**Issue by nawazawanswl** [ImpulseAdventure/GUIslice-Builder#146] opened 2021-01-02 13:38 UTC
is it possible to add fonts to " C:\Program Files (x86)\GUIsliceBuilder\fonts\gfx "
if so how...............?????

**Comment by Pconti31** [comment] 2021-01-02 16:13
@nawazawanswl Read the User Guide.
If you have specific questions after that you can post them here for me to answer.

**Comment by Pconti31** [comment] 2021-01-02 16:27
@nawazawanswl User Guide section 5.7.
Paul--

**Comment by nawazawanswl** [comment] 2021-01-03 07:58
i have gone through the documentation and i am..
unable to find any way add my own fonts to " C:\Program Files (x86)\GUIsliceBuilder\fonts\gfx "
i want to add my own fonts in the directory while design time.
i do not want to add them while in runtime..........
hope you understand.

**Comment by nawazawanswl** [comment] 2021-01-03 08:03
ok,
i  read the section and will try it out.
thanks

**Comment by Pconti31** [comment] 2021-01-03 15:36
@nawazawanswl One thing I just noticed that I failed to document is that when you add new font family you need to have at least one font size 10 or less in each style.  You don't need all styles but say you only have PLAIN (shows as Regular in Builder) inside this folder you need one font size 10 or less.
After that you can have as many sizes as you want,  
Paul--

**Comment by nawazawanswl** [comment] 2021-01-03 15:49
oh, that is good know. this can solve but also led to issues.

**Comment by nawazawanswl** [comment] 2021-01-03 15:51
anyway its very useful info and will save time while adding fonts.

**Comment by nawazawanswl** [comment] 2021-01-11 17:04
thanks, 
i successfully added fonts to to builder directory and they work as expected.
1: generate font with ttf2gfx utility online or or provided by @Pconti31 
2: make a new folder and past them there.
3: open guisllice and start using.

**Comment by Pconti31** [comment] 2021-01-11 18:15
@nawazawanswl Thank you for your feedback.  I hope to move this issue to discussions once I can get it created.
Paul--

**Comment by darkbull** [comment] 2021-01-15 13:12
@Pconti31 Is there any examples demonstrate how to add category "FONT_SIM"? I read document many times, but with no luck. My target-platform is tft-espi, I want to use smooth font, here is my config:

<img width="622" alt="Xnip2021-01-15_21-07-14" src="https://user-images.githubusercontent.com/1897112/104730823-aec70200-5775-11eb-9efe-c899ba820460.png">

error log is:
<img width="791" alt="Xnip2021-01-15_21-12-01" src="https://user-images.githubusercontent.com/1897112/104731219-5e9c6f80-5776-11eb-80b9-35770cb05af7.png">

**Comment by Pconti31** [comment] 2021-01-15 14:05
@darkbull I can do you one better.  I have new builder that will support smoothfonts.  Instead of using FONT_SIM we will have FONT_VLW.  I This version is setup for google's Noto BOLD.   If you want anyother font you will still need to edit the builder_fonts.json but it should be simple to see how to modify it for your new font.   Also, you will need to add at least one size 18 or less.  
The confusing thing here is that adafruit uses a font dpi of 141 and the smooth fonts use 72 to they are half the size of adafruits gfx fonts.   So if you want size something the size of adafruits 12 font you need smoothfont size 23 or 24.

Also note that only *.vlw fonts stored in spiffs is supported by GUIslice API.  The falsh version will crash and burn.  I have patch for that but in the meantime stay way from smoothfonts stired in flash.

If you are will to beta test this new version let me know and I'll post a download link.
Paul--

**Comment by darkbull** [comment] 2021-01-15 15:01
@Pconti31 Thanks for your prompt reply. By reading the source code, I can add FONT_SIM now. This is my config:
<img width="638" alt="Xnip2021-01-15_22-21-39" src="https://user-images.githubusercontent.com/1897112/104738702-d374a700-5780-11eb-8f74-681f2f2ad0b7.png">
Builder can show Chinese now:
<img width="1008" alt="Xnip2021-01-15_22-22-52" src="https://user-images.githubusercontent.com/1897112/104738770-e7200d80-5780-11eb-8d6f-bace9df0c8fd.png">

But there's some problems.
1. Re-open project, Builder crash
2. Upload firmware to esp32, endless loop restart

**Comment by darkbull** [comment] 2021-01-15 15:08
> The confusing thing here is that adafruit uses a font dpi of 141 and the smooth fonts use 72 to they are half the size of adafruits gfx fonts. So if you want size something the size of adafruits 12 font you need smoothfont size 23 or 24.

happy to try

**Comment by Pconti31** [comment] 2021-01-15 15:28
@darkbull 
First, you are trying to use a smoothfont stored in a header (flash).  As I told you above this crashes your esp32.  GUIslice API doesn't currently support flash based smooth fonts (it sets it up as Adafruit GFX font causing the crash).   If you can use vlw font stored in spiffs I can make a builder download available. You will need to edit the json file for your chinese font but can most likely use the NotoBold as a guide.

The Builder problem you have is that it needs to simulate (not use) your desired font.  You need to pick one of the Java built-in fonts which limits you to:
-  "logicalName": "Monospaced"
-  "logicalName": "SansSerif"
-  "logicalName": "Serif"

If you use my beta 0.16.b6 Builder you copy your truetype font to a sub folder in GUIsliceBuilder/fonts/vlw.  Note its a truetype font (the one you used to create your *.vlw files) since the Builder doesn't read or understand vlw format.   Once you edit the json file the Builder will use your TrueType font and not use the Java builtin fonts and the generated code will work with GUIslice API.  Of course, you will need to create a sub folder called data in your project and load the vlw fonts into spiffs.   

Or you can just wait until I finish testing 0.16.b006 which should take another week or two before release.   One thing I think could still be broken is the character code translations in the generated code so that's what is holding up release.
Paul--

**Comment by Pconti31** [comment] 2021-01-15 15:34
@darkbull If you want to help testing I do need to know what version to build, 
Windows, Linux or apple osx.
Paul--

**Comment by darkbull** [comment] 2021-01-15 23:31
Paul, OSX .  good job

**Comment by Pconti31** [comment] 2021-01-15 23:41
@darkbull Ok, here you go.  Let me know of any issues or questions.
[Builder OSX Beta 0.16.b6](https://drive.google.com/file/d/1o3PS4sAndzYyzBrkg4-vw2fjXUSzZ3v4/view?usp=sharing)

**Comment by darkbull** [comment] 2021-01-16 01:23
> @darkbull Ok, here you go. Let me know of any issues or questions.
> [Builder OSX Beta 0.16.b6](https://drive.google.com/file/d/1o3PS4sAndzYyzBrkg4-vw2fjXUSzZ3v4/view?usp=sharing)

Got it.  OK, I'll reply feedback in some days.

**Comment by darkbull** [comment] 2021-01-18 03:06
@Pconti31 Paul, builder crash when re-open project, active any Widgets which hold Chinese font, eg: "你好"
<img width="907" alt="Xnip2021-01-18_11-01-56" src="https://user-images.githubusercontent.com/1897112/104867820-b73d5980-597c-11eb-9786-20097e1c0d0b.png">
<img width="665" alt="Xnip2021-01-18_11-02-18" src="https://user-images.githubusercontent.com/1897112/104867823-bad0e080-597c-11eb-97f0-4742c86ca81c.png">
My SMOOTH-FONT config:
<img width="472" alt="Xnip2021-01-18_11-03-55" src="https://user-images.githubusercontent.com/1897112/104867889-de942680-597c-11eb-92aa-4d29d0721fa2.png">
My ttf:
[ttf.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5827545/ttf.zip)

**Comment by Pconti31** [comment] 2021-01-18 13:53
@darkbull Ugh!  Anyway that's why we do testing!
You font is helpful but I still need a couple of items from you to debug this.
Please zip up your project folder and zip up your edited builder_fonts.json file and zip up
GUIsliceBuilder/logs. do not delete any files.
The snapshot you posted looks fine but maybe something else is wrong since it seems the builder thinks you are using a Adafruit classic "builtin" font instead of your vlw font.

I'll debug as far as I can with what you have already zipped.  Maybe we will get luckly.
Paul--

**Comment by Pconti31** [comment] 2021-01-18 14:37
@darkbull Sorry, but I used your font and created a single text element in a project I called test-chinese pasting your chinese text string.
Saved the project, did a code generation, loaded your font into spiffs, complied and ran the program and it
showed the chinese text.  Hooray!  I was worried that would not work.
Then I reopened the saved project without any crash.  So I really need your files to determine what is happening.
The crash is almost like you tried to open the project with a non beta GUIsliceBuilder that didn't know about vlw fonts.
attached is my test project and my json file.

[builder_fonts.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5830804/builder_fonts.zip)
[test-chinese.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5830808/test-chinese.zip)
Paul--

**Comment by Pconti31** [comment] 2021-01-18 15:03
@darkbull Some good news, in manner of speaking.  I reproduced the crash using the builder posted.
Seems when I run the builder inside Eclipse IDE it works fine but crashes with the release version.
I won't need your files to debug.   I'll post a new link once I figure out why this is happening.
Paul--

**Comment by nawazawanswl** [comment] 2021-01-18 15:28
@Pconti31 
sorry to bother,
i have had same issue with a previous version.
whenever i changed some object in a guislice project i faced a crash.
but when i did it with save as it never crashed , but i always saved in a different folder and copied it back from there to the original project folder.
later i removed the installation and reinstalled and it was ok.
the problem was overwriting .ino file.
may be this can help a bit.
anyway can you @Pconti31  provide a test version for windows.
i also want to test it ??

**Comment by Pconti31** [comment] 2021-01-18 15:45
@darkbull 
@nawazawanswl 
Ok, I found the problem. (I hope!)
I have attached beta 0.16.b6-1018 for OSX and Windows.
Note:  The Chinese font is already included.   You will of course need to add your font to REAL 0.16.b6 release when that is made available.  This is because I'm not sure of the copyrights on the Chinese font so I can't really add it to the project.

[builder-osx-0.16.b006-SNAPSHOT-0118.zip](https://drive.google.com/file/d/1JAIVI4m5uK-_0JqHUjhrUxB2vGjZAYmW/view?usp=sharing)
[builder-win-0.16.b006-SNAPSHOT-0118](https://drive.google.com/file/d/1c06exChMVWKDTcHbqwtLa0pcfDNfmD7o/view?usp=sharing)

Hopefully, this will work a little better.
Any crashes require the actual project folder zipped and GUIsliceBuilder/logs zipped for me to debug.
Paul--

Paul--

**Comment by Pconti31** [comment] 2021-01-18 19:02
For any bug reports on fonts handling;  If you are using a custom font (not the Chinese one already provided) please also zip that along with the edited builder_fonts.json file.
Paul--

**Comment by darkbull** [comment] 2021-01-19 01:00
@Pconti31 Thanks for your grate job and realtime update!  I use latest builder(builder-osx-0.16.b006-SNAPSHOT-0118.zip), now working perfectly. 
I will keep giving feedback. Thanks~~

**Comment by Pconti31** [comment] 2021-01-19 14:09
@nawazawanswl I just noticed you are doing backups by moving your files around.
You shouldn't need to do that.  I designed the builder to do backups for you.
When you do a save it renames your *.prj file to *.prj.bak.  Before doing that it looks to see if a *.prj.bak already exists if so it renames the *.prj.bak to *.prj.##N where goes from 1 to however max number it needs to be to make the file unique.  It then moves the file to a sub folder called gui_backup.  You can always get back to an earlier
version by simply renaming the file back to *.prj.  You just need to check date and times.  The same goes for your *.ino file.  Whenever you do a code generation the same algorithm is used but is with *.ino instead of *.prj.
Just though you might want to know.  

Paul--

**Comment by Pconti31** [comment] 2021-01-20 15:10
With the Release 0f 0.16.b006 I'm closing this topic.
Any future problem will require a new issue topic to be created.
Paul--

**Closed by Pconti31** 2021-01-20 15:10 UTC
Labels: documentation, question
