### ISSUE TITLE
Main application crash

### ISSUE THREAD

**Issue by rustedgear** [ImpulseAdventure/GUIslice-Builder#151] opened 2021-01-24 19:38 UTC
crash when just moving the cursor around within the window. It seems to be inconsistent when it happens. Sometimes I can get a few tasks done and others I can just barely open up the program. 

**To Reproduce**
I believe it is the hover over text for the application buttons. 

**Expected behavior**
a program that does not crash when just moving the cursor around within the window.

**Crash log / Project files**
attached

**Screenshots**
N/A

**Version**
- Builder version:0.16.B006
- OS: Mac OS 10.15.7

**Additional context**
I have both Arduino IDE and Teensyduino installed. 
[Archive.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5863020/Archive.zip)

**Comment by Pconti31** [comment] 2021-01-24 20:29
@rustedgear Yes, seems to a problem with OSX and Multiple line tooltips.
I'll look into it.
Paul--

**Comment by rustedgear** [comment] 2021-01-24 20:30
It would just be a bandaid but could there be a toggle off of the tooltips in the options?

**Comment by Pconti31** [comment] 2021-01-24 21:07
@rustedgear I just built one without tooltips if you are running on a Mac but could you try them one at a time to see if particular one is causing the problem?  I hate to remove them all if its only a couple that has problem.
If not, I'll post a down load for you to try.
Paul--

**Comment by Pconti31** [comment] 2021-01-24 21:13
@rustedgear Here is a snapshot without tooltips.
Let me know if it works for you.
[Snapshot](https://drive.google.com/file/d/1u306rJZlqTGgbxSFTwnb3b-j2REhBVkR/view?usp=sharing)
Paul--

**Comment by rustedgear** [comment] 2021-01-24 21:25
@Pconti31 Thanks for being so awesome and tackling this. It looks like it is actually when you get the tooltip the second time. I was able to get the error to pop up on all buttons on the second hover over. This occurs whether it is repeat hover over or hovering over a different button. Once a tooltip has been shown it crashes if it tries to show another. Now that I know the behavior I can avoid it a bit better.

**Comment by Pconti31** [comment] 2021-01-24 22:40
@rustedgear I wonder if its theme related.  What theme are you using?
If you get the chance try the snapshot I posted for you.
Paul--

**Comment by rustedgear** [comment] 2021-01-24 22:58
@Pconti31 I have used the snapshot a bit and without the tooltips it seems to be more stable.

I am just using the dark theme. Nothing really special as per themes,extra settings, or mods. It is a Retina MacBook Pro.  I am running the Java 15 jdk. I tried uninstalling that but it did not change up the mannerisms. 

Additionally I did try it on my PC (Win 10) and 0.16 would not boot. The arduino IDE is installed on that machine as well. Though possibly I am missing something else on that machine.

**Comment by Pconti31** [comment] 2021-01-25 13:15
@rustedgear Ah!   The problem is likely your Java 15.  Java 14 and above and above causes problems.
We use Java 8 due to Oracle's licensing and have tested with Java 9 and 11.   
Since I don't own a Mac I have no idea how you can roll back to earlier Java but I can tell you that more problems will likely surface.  If you work it out please post the solution here so I can add it to the FAQ.
Paul--

**Comment by Pconti31** [comment] 2021-02-06 15:39
Closing this issue with release of 0.16.b007 and a new ribbon bar that hopefully will allow tooltips to work again on apple osx.  Can be reopened if tooltip still crashes.
Paul--

**Closed by Pconti31** 2021-02-06 15:39 UTC
