### ISSUE TITLE
Builder: mouse very slow when E_PROJECT_OPTIONS (LinuxX)

### ISSUE THREAD

**Issue by pierbout** [ImpulseAdventure/GUIslice-Builder#114] opened 2020-09-08 09:29 UTC
### Describe the bug
In the builder, when the E_PROJECT_OPTIONS pannel is selected, the mouse becomes very slow (at least on Linux Mint 19).
Then, if select E_PG_MAIN pannel again, the mouse reaction is normal again.

### Device hardware
-Linux Mint 19
- openjdk 11.0.7 2020-04-14
      OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
      OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
-  *MCU*:  ATmega 328P
- *Display with link*:  Adafruit ILI9225
- *GUIslice config selected*:  `ard-adagfx-ili9225` or `ard-adagfx-ili9225-due`

### Checklist to try first
*Most display/touch issues can be identified by working through the steps in the [Configuring GUIslice](https://github.com/ImpulseAdventure/GUIslice/wiki/Configuring-GUIslice) guide.*

*Please confirm whether:*
- *Display works correctly with standalone display driver library examples (eg. TFT_eSPI graphicstest, Adafruit graphicstest, etc.) without GUIslice:* yes
- *Touch works correctly with standalone touch library examples without GUIslice:* ???

### Expected behavior
The mouse reaction should not depend on the selected pannel. It should be always the same

### Additional info
We don't often need to go to the E_PROJECT_OPTIONS pannel, so this is not a big problem. Only a bit annoying.

**Comment by Pconti31** [comment] 2020-09-08 12:23
@pierbout Thanks for the info.  There should be a series of log files inside GUIsliceBuilder/logs
Please delete them.
Then open the builder again, reproduce the problem, close the builder and post a zip of the builder.log file I'll look it over to see if anything is off.  Are you using Arduino IDE? If so, you can point the builder to use its Java by editing GUIslice.sh and changing JAVA_HOME to point to arduino/java.  I mention this because you are using Java 11 which is NOT supported by the Builder.  

The Builder wiki installation  [https://github.com/ImpulseAdventure/GUIslice/wiki/Builder-_-Installation-_-LINUX](url) 
is clearly specific about using java 8 (1.8) which is the same one Arduino IDE uses.   Nevertheless, I have used it against Java 11 on occasion without problems so I will look into this further with your help.
Paul--

**Comment by pierbout** [comment] 2020-09-09 08:29
Hello Paul.

Reinstalling the GUIslice-builder with the Arduino IDE Java did not solve this issue. The behaviour remains identical.

$  /home/pierre/Téléchargements/arduino-1.8.12/java/bin/java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

$ export JAVA_HOME=/home/pierre/Téléchargements/arduino-1.8.12/java/

$ cd ~/GUIsliceBuilder

$ ./GUIslice.sh
2020-09-09 10:19:19,621 main DEBUG Initializing configuration XmlConfiguration[location=jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml]
2020-09-09 10:19:19,625 main DEBUG Installed script engines
2020-09-09 10:19:19,829 main DEBUG Oracle Nashorn Version: 1.8.0_191, Language: ECMAScript, Threading: Not Thread Safe, Compile: true, Names: {nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript}
2020-09-09 10:19:19,829 main DEBUG PluginManager 'Core' found 112 plugins
2020-09-09 10:19:19,829 main DEBUG PluginManager 'Level' found 0 plugins
2020-09-09 10:19:19,833 main DEBUG PluginManager 'Lookup' found 13 plugins
2020-09-09 10:19:19,834 main DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2020-09-09 10:19:19,842 main DEBUG PluginManager 'TypeConverter' found 26 plugins
2020-09-09 10:19:19,852 main DEBUG PatternLayout$Builder(pattern="%d %p %m%n", PatternSelector=null, Configuration(jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2020-09-09 10:19:19,852 main DEBUG PluginManager 'Converter' found 41 plugins
2020-09-09 10:19:19,859 main DEBUG Building Plugin[name=TimeBasedTriggeringPolicy, class=org.apache.logging.log4j.core.appender.rolling.TimeBasedTriggeringPolicy].
2020-09-09 10:19:19,864 main DEBUG createPolicy(interval="1", modulate="null")
2020-09-09 10:19:19,865 main DEBUG Building Plugin[name=Policies, class=org.apache.logging.log4j.core.appender.rolling.CompositeTriggeringPolicy].
2020-09-09 10:19:19,865 main DEBUG createPolicy(={TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=false)})
2020-09-09 10:19:19,865 main DEBUG Building Plugin[name=DefaultRolloverStrategy, class=org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy].
2020-09-09 10:19:19,867 main DEBUG createStrategy(max="5", min="null", fileIndex="null", compressionLevel="null", ={}, stopCustomActionsOnError="true", Configuration(jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml))
2020-09-09 10:19:19,867 main DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.RollingFileAppender].
2020-09-09 10:19:19,873 main DEBUG RollingFileAppender$Builder(fileName="logs/builder.log", filePattern="logs/builder-%d{MM-dd-yyyy}-%i.log.zip", append="null", locking="null", Policies(CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=false)])), DefaultRolloverStrategy(DefaultRolloverStrategy(min=1, max=5, useMax=true)), advertise="null", advertiseUri="null", createOnDemand="null", bufferedIo="null", bufferSize="null", immediateFlush="false", ignoreExceptions="null", PatternLayout(%d %p %m%n), name="RollingFile", Configuration(jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml), Filter=null)
2020-09-09 10:19:19,875 main DEBUG Starting RollingFileManager logs/builder.log
2020-09-09 10:19:19,876 main DEBUG PluginManager 'FileConverter' found 2 plugins
2020-09-09 10:19:19,878 main DEBUG Setting prev file time to 2020-09-09T10:19:05.000+0200
2020-09-09 10:19:19,879 main DEBUG Initializing triggering policy CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=false)])
2020-09-09 10:19:19,879 main DEBUG Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
2020-09-09 10:19:19,880 main DEBUG createAppenders(={RollingFile})
2020-09-09 10:19:19,880 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2020-09-09 10:19:19,880 main DEBUG createAppenderRef(ref="RollingFile", level="null", Filter=null)
2020-09-09 10:19:19,880 main DEBUG Building Plugin[name=logger, class=org.apache.logging.log4j.core.config.LoggerConfig].
2020-09-09 10:19:19,882 main DEBUG createLogger(additivity="false", level="DEBUG", name="Builder", includeLocation="null", ={RollingFile}, ={}, Configuration(jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml), Filter=null)
2020-09-09 10:19:19,883 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2020-09-09 10:19:19,883 main DEBUG createAppenderRef(ref="RollingFile", level="null", Filter=null)
2020-09-09 10:19:19,884 main DEBUG Building Plugin[name=root, class=org.apache.logging.log4j.core.config.LoggerConfig$RootLogger].
2020-09-09 10:19:19,885 main DEBUG createLogger(additivity="null", level="TRACE", includeLocation="null", ={RollingFile}, ={}, Configuration(jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml), Filter=null)
2020-09-09 10:19:19,885 main DEBUG Building Plugin[name=loggers, class=org.apache.logging.log4j.core.config.LoggersPlugin].
2020-09-09 10:19:19,886 main DEBUG createLoggers(={Builder, root})
2020-09-09 10:19:19,887 main DEBUG Configuration XmlConfiguration[location=jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml] initialized
2020-09-09 10:19:19,887 main DEBUG Starting configuration XmlConfiguration[location=jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml]
2020-09-09 10:19:19,887 main DEBUG Started configuration XmlConfiguration[location=jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml] OK.
2020-09-09 10:19:19,888 main DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false-1
2020-09-09 10:19:19,888 main DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false-1, all resources released: true
2020-09-09 10:19:19,888 main DEBUG Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@2f333739 OK
2020-09-09 10:19:19,925 main DEBUG Registering MBean org.apache.logging.log4j2:type=4e25154f
2020-09-09 10:19:19,927 main DEBUG Registering MBean org.apache.logging.log4j2:type=4e25154f,component=StatusLogger
2020-09-09 10:19:19,928 main DEBUG Registering MBean org.apache.logging.log4j2:type=4e25154f,component=ContextSelector
2020-09-09 10:19:19,929 main DEBUG Registering MBean org.apache.logging.log4j2:type=4e25154f,component=Loggers,name=
2020-09-09 10:19:19,930 main DEBUG Registering MBean org.apache.logging.log4j2:type=4e25154f,component=Loggers,name=Builder
2020-09-09 10:19:19,930 main DEBUG Registering MBean org.apache.logging.log4j2:type=4e25154f,component=Appenders,name=RollingFile
2020-09-09 10:19:19,932 main DEBUG Reconfiguration complete for context[name=4e25154f] at URI jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml (org.apache.logging.log4j.core.LoggerContext@51399530) with optional ClassLoader: null
2020-09-09 10:19:19,932 main DEBUG Shutdown hook enabled. Registering a new one.
2020-09-09 10:19:19,933 main DEBUG LoggerContext[name=4e25154f, org.apache.logging.log4j.core.LoggerContext@51399530] started OK.


[CTRL + C ]


^C
2020-09-09 10:22:24,876 pool-1-thread-1 DEBUG Stopping LoggerContext[name=4e25154f, org.apache.logging.log4j.core.LoggerContext@51399530]
2020-09-09 10:22:24,877 pool-1-thread-1 DEBUG Stopping LoggerContext[name=4e25154f, org.apache.logging.log4j.core.LoggerContext@51399530]...
2020-09-09 10:22:24,881 pool-1-thread-1 DEBUG Shutting down RollingFileManager logs/builder.log
2020-09-09 10:22:24,881 pool-1-thread-1 DEBUG Shut down RollingFileManager logs/builder.log, all resources released: true
2020-09-09 10:22:24,881 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=jar:file:/home/pierre/GUIsliceBuilder/lib/builder-0.15.b004.jar!/resources/log4j2.xml] OK
2020-09-09 10:22:24,881 pool-1-thread-1 DEBUG Stopped LoggerContext[name=4e25154f, org.apache.logging.log4j.core.LoggerContext@51399530]...




$ cat  ~/GUIsliceBuilder/logs/builder.log
2020-09-09 10:19:19,936 DEBUG Builder started-java version: 1.8 osys: linux
2020-09-09 10:19:20,001 DEBUG FontFactory Initialized
2020-09-09 10:19:20,481 DEBUG TV-add page: Node: key=Project$1 enum=E_PROJECT_OPTIONS type=Project
2020-09-09 10:19:20,489 DEBUG PropManager recv: OBJECT_SELECTED_TREEVIEW: Project$1 Parent: Root
2020-09-09 10:19:20,489 DEBUG Controller recv: OBJECT_SELECTED_TREEVIEW: Project$1 Parent: Root
2020-09-09 10:19:20,491 DEBUG TreeView recv: PAGE_TAB_CHANGE Key: Page$1
2020-09-09 10:19:20,493 DEBUG TV-add page: Node: key=Page$1 enum=E_PG_MAIN type=Page
2020-09-09 10:19:20,495 DEBUG PropManager recv: OBJECT_SELECTED_TREEVIEW: Page$1 Parent: Root
2020-09-09 10:19:20,495 DEBUG Controller recv: OBJECT_SELECTED_TREEVIEW: Page$1 Parent: Root
2020-09-09 10:19:20,496 DEBUG New Project
2020-09-09 10:19:29,236 DEBUG TreeView recv: PAGE_TAB_CHANGE Key: Project$1
2020-09-09 10:21:17,654 DEBUG TreeView recv: PAGE_TAB_CHANGE Key: Page$1

**Comment by pierbout** [comment] 2020-09-09 08:32
Paul,

No problem about the deadlines. There is no emergency, and the builder is perfectly usable despite this issue. I opened this issue to help you make the builder even better.

Thank you for your help, good luck, and we keep in touch.

**Comment by Pconti31** [comment] 2020-09-09 21:26
The code for each tab is the same so its hard to figure its really the builder though certainly possible.
I'll get to mint eventually. In the meantime maybe this really old topic might help
Have a look at "How do I solve periodic mouse lag on Linux Mint (MATE)?" [https://superuser.com/questions/528727/how-do-i-solve-periodic-mouse-lag-on-linux-mint-mate](url)

Paul--

**Comment by Pconti31** [comment] 2021-02-06 15:41
Closing this issue with the Release 0.16.b007 and the new RibbonBar implemenation.
Can be reopened if this still occurs.
Paul--

**Closed by Pconti31** 2021-02-06 15:41 UTC
