### ISSUE TITLE
Request: Project Screen Size change with change of all existed elements size. 

### ISSUE THREAD

**Issue by nadjet09** [ImpulseAdventure/GUIslice-Builder#192] opened 2022-02-14 13:04 UTC
**Describe the solution you'd like**
It would be so helpful to be able to change the screen size and all lines, boxes, text, images, or any existed element in the project would shrink to the same ratio of the new display. 

**Additional context**
after getting so deep in creating a GuiSlice project with hundreds of elements it become nightmare to go and change every element to the new size (for example I went from 320x240 to 480x320 and I did the changes manually before, now I need another project from 480x320 to 320x240), while it would be done by mathematical equation and scan of of all element to set to new height/width and X/Y position.

**Comment by Pconti31** [comment] 2022-02-14 14:28
@nadjet09 Fonts seem complicated since they are not scaled and not all sizes exist.  You might have to select new font(s) mappings yourself inside a dialog that takes the new screen size.

So what mathematical equation are you thinking of?

Paul--

**Comment by Pconti31** [comment] 2022-02-15 17:04
@nadjet09 Fixed in Release 0.17.b07.  Not much testing done so let me know if any problems occur.
You need to first go to the Project options, change display size and then select the Page Layout tab->Scale
answer questions of the previous screen size and select OK.  

WARNING! If shrinking screen size do not leave Project Options with the new display  height and width
without first going to Page Layout and choosing the new Scale command or you may crash and burn due to 
existing elements being placed beyond screen limits.  I tried to trap these cases but as I said very little testing.

I'll close this if you notify me of things working or if a few days go by without any feedback.
Paul--

**Comment by nadjet09** [comment] 2022-02-15 19:14
I tried again and it seemed working with some pages. in this clip I showed E_PG_Pup2 as a popup page and E_PG_Main as a page before changes, and after I did the changes the E_PG_Pup2 was resized, but when I clicked on the E_PG_Main tab, the GUISlice crashed. could that be related to the page type or too many elements in one page cause the issue?
https://youtu.be/pAYSJq_VVbA

**Comment by Pconti31** [comment] 2022-02-15 19:27
@nadjet09 The first set of crashes are being caused by a Line Element on your page.  No idea why.

Any chance you could post a zip of your project folder and  *.prj so I can try and debug the *.prj file?
I don't need to deal with any output files.

Are you growing or shrinking your display?

Paul--

**Comment by nadjet09** [comment] 2022-02-15 19:33
Sure, My project contains some customized GFX fonts that you may have to add to the GUIbuilder.
[GuiSliceExm.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/8074074/GuiSliceExm.zip)
.

**Comment by nadjet09** [comment] 2022-02-15 19:47
I'm shrinking the display now from 320x480 to 240x320

**Comment by Pconti31** [comment] 2022-02-15 20:25
@nadjet09 Ok, I see the problem.   It's with the Line Element model.  It is broken.  Only showed up because of the scaling. 
 Basically I rip through all elements and call base functions in the superclass Widget Model to change x,y,height and width. Problem is that Line Element model starts on  duplicate subscripts for length of line with Y, is Vertical with width, and Fill color with Height.  So when setting those values at the superclass I was wiping those values out.  Ugh!
I need to cut back on my drinking!  I need to work out a way to upgrade existing Line Elements.  I'll post a update 0.17.b08 tomorrow sometime.
Paul--

**Comment by nadjet09** [comment] 2022-02-15 21:07
that sounds great, I had a look at the source code yesterday and I can slightly relate to what you described, but it still looks too deep for me to jump in and do some work in it.

**Comment by Pconti31** [comment] 2022-02-16 19:18
@nadjet09 Ok, I thing things are working correctly now.   I was able to provide scaling for fonts although manual changes may still be needed.   The Builtin (GLCD) fonts are ignored and if no font can be found that comes close to the proper scaling ratio I just leave it alone.  Let me know if it works better for you now and I'll close this issue.
If you like the way it works don't forget to add a star to the repository.  People tend to forget my project is different from the API.
Paul--

**Comment by nadjet09** [comment] 2022-02-16 19:58
Hi @Pconti31, It's performing better now, I didn't have crashes.
but there is some height scaling issue. I noticed the width changes according to scale but the height still bit out of the frame.
some text in the bottom when they still out of the frame, their height convert to over 600pixel.
in this clip I tried to demonstrate what I described.
https://youtu.be/9MNgYy7DxSI 
thank you so much for all the effort

**Comment by nadjet09** [comment] 2022-02-16 20:10
Well According to what I noticed here, is the ratio of width 240/320 = 0.75 and 320/480 = 0.66667, so those ratio looks good for the width/height change but the x/y are both calculated based on 0.75

**Comment by nadjet09** [comment] 2022-02-16 20:20
I don't know if you saw my prev. comments but just wanted mention this if it could help
at Pagepane.java line 1182
I saw this ratioX used for both X/Y
newX = (int)(((double)m.getX() * ratioX) + 0.5);
newY = (int)(((double)m.getY() * ratioX) + 0.5);

**Comment by Pconti31** [comment] 2022-02-16 20:36
@nadjet09 Yes, that would do it.   Third time is the charm!  0.17.b09 coming up.

**Comment by Pconti31** [comment] 2022-02-16 20:56
@nadjet09 Release 0.17.b09 is ready.  Hopefully this is it.

**Comment by nadjet09** [comment] 2022-02-16 21:12
It worked for me, thank you so much

**Comment by Pconti31** [comment] 2022-02-16 23:08
No problem. I'm happy it now working for you.

**Closed by Pconti31** 2022-02-16 23:08 UTC
Labels: enhancement
